# Generated by Django 4.1 on 2022-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_workoutexerciseset"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexerciseset",
            name="reps",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="workoutexerciseset",
            name="weight",
            field=models.FloatField(null=True),
        ),
    ]
