# Generated by Django 4.1 on 2022-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_alter_workoutexerciseset_reps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="created_on",
            field=models.DateTimeField(null=True),
        ),
    ]
