# Generated by Django 4.1 on 2022-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0008_alter_workout_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexerciseset",
            name="rir",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
