# Generated by Django 4.1 on 2022-09-05 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0009_workoutexerciseset_rir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutexerciseset",
            name="weight",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
