# Generated by Django 4.1 on 2022-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0010_alter_workoutexerciseset_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutexerciseset",
            name="reps",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
