# Generated by Django 4.1 on 2022-09-05 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0011_alter_workoutexerciseset_reps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutexerciseset",
            name="rir",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
