# Generated by Django 4.1 on 2022-10-08 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0003_alter_routineexercise_routine"),
        ("workouts", "0012_alter_workoutexerciseset_rir"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="routine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="routines.routine",
            ),
        ),
    ]
